//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbookReaderLib.SomaDbApi {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://pegasus.co.ug/", ConfigurationName="SomaDbApi.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pegasus.co.ug/ExecuteNonQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EbookReaderLib.SomaDbApi.Result ExecuteNonQuery(string conString, string storedProcedureName, string[] Parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pegasus.co.ug/ExecuteSelect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ExecuteSelect(string conString, string storedProcedureName, string[] Parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pegasus.co.ug/ExecuteDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ExecuteDataSet(string conString, string storedProcedureName, string[] Parameters);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://pegasus.co.ug/")]
    public partial class Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusCodeField;
        
        private string statusDescField;
        
        private string numberOfRowsAffectedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusDesc {
            get {
                return this.statusDescField;
            }
            set {
                this.statusDescField = value;
                this.RaisePropertyChanged("StatusDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NumberOfRowsAffected {
            get {
                return this.numberOfRowsAffectedField;
            }
            set {
                this.numberOfRowsAffectedField = value;
                this.RaisePropertyChanged("NumberOfRowsAffected");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : EbookReaderLib.SomaDbApi.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<EbookReaderLib.SomaDbApi.ServiceSoap>, EbookReaderLib.SomaDbApi.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EbookReaderLib.SomaDbApi.Result ExecuteNonQuery(string conString, string storedProcedureName, string[] Parameters) {
            return base.Channel.ExecuteNonQuery(conString, storedProcedureName, Parameters);
        }
        
        public System.Data.DataTable ExecuteSelect(string conString, string storedProcedureName, string[] Parameters) {
            return base.Channel.ExecuteSelect(conString, storedProcedureName, Parameters);
        }
        
        public System.Data.DataSet ExecuteDataSet(string conString, string storedProcedureName, string[] Parameters) {
            return base.Channel.ExecuteDataSet(conString, storedProcedureName, Parameters);
        }
    }
}
